services:
  postgres:
    image: postgres:15
    container_name: pdf2dashboard_postgres
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
      POSTGRES_DB: dashboard_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:10.4.2
    container_name: pdf2dashboard_grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      # <-- thêm hai biến môi trường để kết nối đến renderer
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://pdf2dashboard_grafana:3000/
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - renderer           # đảm bảo renderer được khởi động trước
    links:
      - postgres
      - renderer
    volumes:
      - grafana-storage:/var/lib/grafana

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: pdf2dashboard_renderer
    ports:
      - "8081:8081"
    environment:
      ENABLE_METRICS: "true"

volumes:
  pgdata:
  grafana-storage:
